name: CI / CD Pipeline TP3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Convert repo owner to lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push the Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaoox/tp3-weatherapp:${{ github.run_number }}-latest
          context: ./TP3
          file: ./TP3/Dockerfile
      
      

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

  deploy_to_aci:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        uses: Azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-${{ github.run_number }}
          image: jaoox/tp3-weatherapp:${{ github.run_number }}-latest  # This must match the exact image path used in the push step
          location: francecentral
          environment-variables: API_KEY=${{ secrets.API_KEY }} DNS_NAME_LABEL=devops-${{ github.run_number }}
          name: aci-devops-${{ github.run_number }}
          cpu: 1
          ip-address: Public
          memory: 1.5
          os-type: Linux
          ports: 80
          protocol: TCP
          restart-policy: Always
      
